//@baseURL = http://localhost:4000/api
@baseURL = https://myvehiclesback.herokuapp.com/api
@id = 629d19713047656a1df0a72c
###
// POST - Adiciona veiculo
POST {{baseURL}}/veiculos/
Content-Type: application/json

{
   "tipo": "joaoviniciuszds@outlook.com",
   "marca": "Honda",
   "modelo": "WRV",
   "cor": "Amarelo!",
   "placa": "dfd1458",
   "renavam": "251561658",
   "user_id": "629debb8b4f924e7d68968bb"
}